.\" Man page for encode.c
.\" Steve Meyer - Fall 2014

.TH decode_man 1 "23 November 2014" "CSCI 241" "Oberlin College"

.SH NAME
.B decode
- A program for decompressing text. 

.SH SYNOPSIS
.B decode
<input>
<output>

.SH DESCRIPTION
Decompresses text that was compressed by encode.c

.SH OPTIONS

.IP "input"

Choose the source of input, normally a compressed text file.

.IP "output"

Where the output of the file will go, typically a text file or the command line.

.SH AUTHOR
Steve Meyer (Fall 2014)

.SH BUG
None yet.
