.\" Man page for encode.c
.\" Steve Meyer - Fall 2014

.TH encode_man 1 "23 November 2014" "CSCI 241" "Oberlin College"

.SH NAME
.B encode
- A program for compressing text. 

.SH SYNOPSIS
.B encode
<input>
<output>

.SH DESCRIPTION
Compresses text to later be decompressed by decode.c

.SH OPTIONS

.IP "input"

Choose the source of input, whether it be the command line or a text file ect.

.IP "output"

Where the output of the file will go, typically a text file.

.SH AUTHOR
Steve Meyer (Fall 2014)

.SH BUG
None yet.
